# Generated by Django 5.2.12 on 2026-03-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorchannel',
            name='access_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='creatorchannel',
            name='credential_status',
            field=models.CharField(blank=True, choices=[('known', 'Known'), ('held_by_creator', 'Held by creator'), ('stored_elsewhere', 'Stored elsewhere'), ('needs_reset', 'Needs reset')], max_length=30),
        ),
        migrations.AddField(
            model_name='creatorchannel',
            name='last_access_check_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creatorchannel',
            name='login_identifier',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='creatorchannel',
            name='profile_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='creatorchannel',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
