# Generated by Django 5.2.12 on 2026-03-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_creatorchannel_access_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorchannel',
            name='access_profile_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='creatorchannel',
            name='approved_access_region',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='creatorchannel',
            name='approved_egress_ip',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='creatorchannel',
            name='approved_ip_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='creatorchannel',
            name='last_ip_check_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creatorchannel',
            name='vpn_required',
            field=models.BooleanField(default=False),
        ),
    ]
