# Generated by Django 5.2.12 on 2026-03-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_creatorchannel_access_profile_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='content_ready_status',
            field=models.CharField(blank=True, choices=[('waiting_for_creator', 'Waiting for creator'), ('uploaded', 'Uploaded'), ('ready_to_post', 'Ready to post'), ('posted', 'Posted'), ('blocked', 'Blocked')], max_length=30),
        ),
        migrations.AddField(
            model_name='creator',
            name='content_source_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='content_source_type',
            field=models.CharField(blank=True, choices=[('shared_drive', 'Shared drive'), ('dropbox', 'Dropbox'), ('onedrive', 'OneDrive'), ('telegram', 'Telegram'), ('email', 'Email'), ('internal_storage', 'Internal storage'), ('mixed', 'Mixed'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='creator',
            name='content_source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='creatorchannel',
            name='last_operator_update',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='creatorchannel',
            name='last_operator_update_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
