# Generated by Django 5.2.12 on 2026-03-18 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_creator_content_ready_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorchannel',
            name='handoff_blocker',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='creatorchannel',
            name='handoff_next_action',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='creatorchannel',
            name='handoff_status',
            field=models.CharField(choices=[('clear', 'Clear'), ('needs_action', 'Needs action'), ('blocked', 'Blocked')], default='clear', max_length=20),
        ),
        migrations.AddField(
            model_name='creatorchannel',
            name='last_operator_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_handoff_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
