# Generated by Django 5.2.12 on 2026-03-18 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_creatorchannel_handoff_blocker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorchannel',
            name='handoff_blocker',
        ),
        migrations.RemoveField(
            model_name='creatorchannel',
            name='handoff_next_action',
        ),
        migrations.RemoveField(
            model_name='creatorchannel',
            name='handoff_status',
        ),
        migrations.RemoveField(
            model_name='creatorchannel',
            name='last_operator_updated_by',
        ),
    ]
