# Generated by Django 5.2.12 on 2026-03-22 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_creatorchannel_account_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorchannel',
            name='account_email',
        ),
        migrations.RemoveField(
            model_name='creatorchannel',
            name='account_phone_number',
        ),
    ]
