# Generated by Django 5.2.12 on 2026-03-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_creatorchannel_account_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorchannel',
            name='account_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='creatorchannel',
            name='account_phone_number',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
