# Generated by Django 5.2.12 on 2026-07-08 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_connected_chat_source_identity_v1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadFollowUpStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('warm', 'Warm'), ('open_loop', 'Open loop'), ('later_triggeren', 'Later triggeren'), ('afgekoeld', 'Afgekoeld'), ('review_nodig', 'Review nodig')], max_length=32)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_thread_follow_up_statuses', to=settings.AUTH_USER_MODEL)),
                ('thread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_status', to='core.conversationthread')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_thread_follow_up_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='thread_followup_status_idx'), models.Index(fields=['updated_at'], name='thread_followup_updated_idx')],
            },
        ),
    ]
