# Generated by Django 5.2.12 on 2026-07-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_manual_follow_up_status_v0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmessage',
            name='source_system',
            field=models.CharField(blank=True, choices=[('mara_chat', 'Mara chat'), ('chatties', 'Chatties'), ('eurotikken', 'Eurotikken')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='conversationthread',
            name='source_system',
            field=models.CharField(choices=[('mara_chat', 'Mara chat'), ('chatties', 'Chatties'), ('eurotikken', 'Eurotikken')], default='mara_chat', max_length=32),
        ),
    ]
