# Generated by Django 5.2.16 on 2026-07-27 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_conversationthread_participant_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationContextSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_version', models.CharField(max_length=80)),
                ('source_sha256', models.CharField(max_length=64)),
                ('profile_context', models.JSONField(blank=True, default=dict)),
                ('customer_context', models.JSONField(blank=True, default=dict)),
                ('profile_media', models.JSONField(blank=True, default=list)),
                ('customer_media', models.JSONField(blank=True, default=list)),
                ('data_quality', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('thread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='context_snapshot', to='core.conversationthread')),
            ],
        ),
    ]
