# Generated by Django 5.2.12 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_conversation_context_snapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="threadfollowupstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("warm", "Warm"),
                    ("open_loop", "Open loop"),
                    ("later_triggeren", "Trigger later"),
                    ("afgekoeld", "Cooled off"),
                    ("review_nodig", "Review required"),
                ],
                max_length=32,
            ),
        ),
    ]
